version: "3.1"

services:
  my_mongo_db:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo:/data/db

  my_maria_db:
    image: mariadb:10.6.14
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
    volumes:
      - ./db/maria:/var/lib/mysql

  my_server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:4000
    environment:
      # Mongo environment variables:
      - DB_MONGO_HOST=my_mongo_db
      - DB_PROTOCOL=$DB_PROTOCOL

      # MySQL/MariaDB environment variables:
      - DB_MARIA_HOST=my_maria_db
      - DB_MARIA_USER=root
      - DB_MARIA_PASSWORD=$MARIADB_ROOT_PASSWORD

  